### ISSUE TITLE
Relax `semigroupoids` upper bound

### ISSUE THREAD

**Issue by coot** [nikita-volkov/strict-list#1]
`semigroupoids-6.0.0.1` was released recently.

**Comment by coot** [comment]
Ping, could you add a new revision in `Hackage`?

**Comment by ysangkok** [comment]
Would be cool with a revision since it would allow for the package to stay in Stackage:

* https://github.com/commercialhaskell/stackage/issues/6909

**Comment by ysangkok** [comment]
@nikita-volkov Just a ping in case the notifications are not working without a mention. Please see the other comments

**Comment by nikita-volkov** [comment]
Oops. Was unsubscribed for some reason. Thanks for the ping!

**Comment by nikita-volkov** [comment]
Released
